name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assemble

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit test with Gradle
        run: ./gradlew koverXmlReport

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/test-results/**/*.xml
            **/test-results/**/*.trx
            **/test-results/**/*.json
      - name: Add coverage to PR
        id: kover
        uses: mi-kas/kover-report@v1
        if: always()
        with:
          path: |
            ${{ github.workspace }}/model/build/reports/kover/report.xml
          token: ${{github.token}}
          title: Code Coverage
          update-comment: false
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE